create table if not exists k_wallet (
    id bigint generated by default as identity primary key not null ,
    member_id varchar(30) not null unique ,
    full_name varchar(100),
    no_rekening varchar(100) unique ,
    gen_va varchar(8) not null unique ,
    balance numeric(15,2),
    currency varchar(5),
    symbol varchar(5),
    status varchar(100),
    is_active bool,
    created_at timestamp with time zone default current_timestamp,
    updated_at timestamp with time zone default current_timestamp,
    deleted_at timestamp with time zone default null
)