create table if not exists virtual_account_k_wallet (
    id bigint generated by default as identity primary key not null,
    k_wallet_id bigint not null ,
    virtual_account varchar(50),
    bank varchar(50),
    bank_code varchar(50),
    created_at timestamp with time zone default current_timestamp,
    updated_at timestamp with time zone default current_timestamp,
    deleted_at timestamp with time zone default null
)