create table if not exists channel_images (
    id bigint generated by default as identity primary key ,
    channel_id bigint null ,
    file_name varchar(50) ,
    size_type varchar(5) ,
    geometric_type varchar(15) ,
    created_at timestamp with time zone default current_timestamp,
    updated_at timestamp with time zone default current_timestamp,
    deleted_at timestamp with time zone default null
)