create table if not exists k_wallet_transaction(
    id bigint generated always as identity primary key not null ,
    k_wallet_id bigint not null ,
    k_wallet_type_transaction_id bigint,
    payment_id varchar(50),
    title varchar(30),
    payment_code varchar(50) unique not null ,
    transaction_code varchar(50) unique not null ,
    transaction_type varchar(50),
    direction varchar(10),
    counterparty_name varchar(100),
    counterparty_bank varchar(25),
    payment_channel varchar(50),
    description text,
    balance numeric(15,2),
    debit numeric(15,2),
    credit numeric(15,2),
    amount numeric(15,2),
    currency varchar(5),
    symbol varchar(5),
    status varchar(100),
    month numeric(2),
    year numeric(5),
    date date,
    time time,
    datetime timestamp,
    created_at timestamp with time zone default current_timestamp,
    updated_at timestamp with time zone default current_timestamp,
    deleted_at timestamp with time zone default null
)