create table if not exists mas_dion_va_cust_pay_det (
    id int primary key not null ,
    trcd varchar(20) null ,
    trtype varchar(8) null ,
    effect varchar(1) null ,
    etdt timestamp null ,
    trdt timestamp null ,
    custtype varchar(1) null ,
    applyto varchar(20) null ,
    bankCode varchar(20) null ,
    bankDesc varchar(50) null ,
    novac varchar(20) null ,
    dfno varchar(20) null ,
    docno varchar(100) null ,
    refno varchar(100) null ,
    amount numeric(15,2) null ,
    createdt timestamp null ,
    createnm varchar(20) null ,
    updatedt timestamp null ,
    updatenm varchar(20) null,
    postedflag char(1) default '0',
    posteddt timestamp null,
    coa varchar(10) null ,
    rq_uuid varchar(100) null ,
    tipe_dk varchar(1) null ,
    effect_acc varchar(1) null ,
    tipe_dk_acc varchar(1) null
)